#!/bin/bash

# Webhook Bridge - Complete Setup Script
# Auto-generates secure .env file with random passwords and keys

set -e

ENV=${1:-production}
SHOW_PASSWORDS=${SHOW_PASSWORDS:-true}

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Webhook Bridge - Setup Script"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check Python3
if ! command -v python3 &> /dev/null; then
    echo "❌ Python3 not found! Please install Python 3.7+"
    exit 1
fi

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "ℹ️  Keeping existing .env file"
        echo "✅ Setup complete!"
        exit 0
    fi
fi

# Generate secure random keys
echo "🔑 Generating secure keys..."
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
ENCRYPTION_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
WEBHOOK_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
ADMIN_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))")

echo "   ✓ SECRET_KEY generated"
echo "   ✓ ENCRYPTION_KEY generated"
echo "   ✓ WEBHOOK_SECRET generated"
echo "   ✓ ADMIN_PASSWORD generated"
echo ""

# Create root .env file
echo "📝 Creating environment files..."
cat > .env << EOF
# Webhook Bridge - Auto-generated Configuration
# Generated: $(date)
# Environment: $ENV

# ============================================================================
# SECURITY KEYS - Keep these secret!
# ============================================================================
SECRET_KEY=$SECRET_KEY
ENCRYPTION_KEY=$ENCRYPTION_KEY
WEBHOOK_SECRET=$WEBHOOK_SECRET

# ============================================================================
# ADMIN USER
# ============================================================================
ADMIN_USERNAME=admin
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_EMAIL=admin@localhost

# ============================================================================
# APPLICATION SETTINGS
# ============================================================================
ENVIRONMENT=$ENV
DATABASE_URL=sqlite:////data/webhook_bridge.db
HOST=0.0.0.0
PORT=8000

# CORS Origins
CORS_ORIGINS_STR=http://localhost,http://localhost:3000,http://frontend

# Logging
LOG_LEVEL=INFO
JSON_LOGS=false

# Rate Limiting
RATE_LIMIT_ENABLED=true
RATE_LIMIT_PER_MINUTE=100

# Retry Configuration
RETRY_ENABLED=true
RETRY_MAX_ATTEMPTS=3
EOF

# Create frontend .env file
mkdir -p frontend
cat > frontend/.env << EOF
# Frontend Environment Configuration
# Auto-generated by setup script

# Backend API URL (used in development)
VITE_BACKEND_URL=http://localhost:8000

# API Base Path (default /api works with nginx proxy)
VITE_API_URL=/api
EOF

# Create backend .env symlink or copy (for docker-compose)
mkdir -p backend
if [ ! -f backend/.env ]; then
    cat > backend/.env << EOF
# Backend environment - sources from root .env
# This file is auto-generated

SECRET_KEY=$SECRET_KEY
ENCRYPTION_KEY=$ENCRYPTION_KEY
WEBHOOK_SECRET=$WEBHOOK_SECRET
ADMIN_USERNAME=admin
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_EMAIL=admin@localhost
ENVIRONMENT=$ENV
DATABASE_URL=sqlite:///./webhook_bridge.db
HOST=0.0.0.0
PORT=8000
CORS_ORIGINS_STR=http://localhost:3000,http://localhost:5173
LOG_LEVEL=INFO
EOF
fi

# Create data directory
mkdir -p data
chmod 755 data

# Set secure permissions
chmod 600 .env
chmod 600 frontend/.env 2>/dev/null || true
chmod 600 backend/.env

echo "   ✓ Root .env created"
echo "   ✓ Frontend .env created"
echo "   ✓ Backend .env created"
echo "   ✓ Data directory created"
echo ""

echo "✅ Environment files created successfully!"
echo ""

if [ "$SHOW_PASSWORDS" = "true" ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "📋 YOUR ADMIN CREDENTIALS:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "   URL:      http://localhost:3000/login"
    echo "   Username: admin"
    echo "   Password: $ADMIN_PASSWORD"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "⚠️  IMPORTANT:"
    echo "   • Save these credentials NOW!"
    echo "   • File permissions: 600 (owner read/write only)"
    echo "   • Never commit .env to git"
    echo "   • To view later: cat .env | grep ADMIN_PASSWORD"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Next Steps:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1. Start services (will auto-initialize database):"
echo "      docker-compose up -d"
echo ""
echo "   2. Check logs:"
echo "      docker-compose logs -f backend"
echo ""
echo "   3. Access application:"
echo "      • Frontend: http://localhost:3000"
echo "      • Backend API: http://localhost:8000"
echo "      • API Docs: http://localhost:8000/docs"
echo ""
echo "   4. View admin password:"
echo "      cat .env | grep ADMIN_PASSWORD"
echo ""
echo "   5. Test webhook:"
echo "      curl http://localhost:8000/api/webhook-test/samples"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 Useful Commands:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   • Rebuild containers:"
echo "      docker-compose build"
echo ""
echo "   • View logs:"
echo "      docker-compose logs -f"
echo ""
echo "   • Restart services:"
echo "      docker-compose restart"
echo ""
echo "   • Stop services:"
echo "      docker-compose down"
echo ""
echo "   • Run backend lint:"
echo "      docker-compose exec backend flake8 app/"
echo ""
echo "   • Run frontend lint:"
echo "      docker-compose exec frontend npm run lint"
echo ""
echo "   • Access backend shell:"
echo "      docker-compose exec backend bash"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ Setup complete! Database will be auto-created on first run."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
